### ISSUE TITLE
Advice on repetitive elements

### ISSUE THREAD

**Issue by cnk113** [ksahlin/isONcorrect#1]
Hello,

I was wondering if it was a good idea to do consensus calling before or after running isONcorrect?
Specifically if our data has transcripts produced from rolling amplication. It would be likely produce higher accuracy after chopping the read into multiple individual subreads for input?

Thanks,
Chang

**Comment by ksahlin** [comment]
Hi Chang,

It really depends on the accuracy of the rolling amplicon correction method. But, assuming the sequences in the rolling amplicon are from the same original sequence and only differ in sequencing errors (i.e., no exon differences) it is an easier problem to consensus correct such sequences than sequences with structural exon differences. 

So, I would think it is better to first produce consensus sequences, then run isONclust and isONcorrect for inter-transcript correction.

However, out of curiosity, it is of course possible to compare the consensus accuracy between the rolling consensus algorithm and isONcorrect by running them on each individual rolling amplicon separately (chopped into subreads for isONcorrect).

Best,
Kristoffer
