### ISSUE TITLE
Phred Score all 10 for corrected reads.

### ISSUE THREAD

**Issue by liscruk** [ksahlin/isONcorrect#11]
Is this expected behavior for corrected reads ?

Reads looks like this:

```
@example_read
CTCTTTTTCCGGCTGGAAC
+
+++++++++++++++++++
```

**Comment by ksahlin** [comment]
Yes, after the correction there are no informative quality scores - they are simply output as `+`. That is, the quality scores should not be used for downstream analysis. However, the accuracy of corrected reads is likely much higher than a Phred score of 10.
