### ISSUE TITLE
why __init__.py is empty?

### ISSUE THREAD

**Issue by Threeman8** [ksahlin/isONcorrect#19]
Hi,
I would like to know why isONcorrect/modules/__init__.py is blank?
What should I write on it?
THX

**Comment by Threeman8** [comment]
When I run 
`./correction_pipeline.sh_o 0.fastq ./output/ 8`
I encountered 
`Traceback (most recent call last):
  File "/miniconda/envs/isoncorrect/bin/isONclust", line 10, in <module>
    from modules import get_sorted_fastq_for_cluster
ImportError: cannot import name 'get_sorted_fastq_for_cluster' from 'modules' (/miniconda/envs/isoncorrect/bin/modules/__init__.py)`

**Comment by ksahlin** [comment]
Hi @Threeman8,

You don't need to write anything in the `__init__` file.
 
Not sure why you get this error, but my guess is that you have isONclust installed outside your `isONcorrect` conda environment. So it finds an isonclust installation outside the environment and gets confused. (haven't seen this cause an error before though, so it's only a guess)

My suggestion is to install isONclust within your isONcorrect environment. This may require uninstalling the other isONclust installation if conda complains.

**Comment by Threeman8** [comment]
Hello, ksahlin.
I will try to create the environment again and install the isoncorrect in this environment.
Thanks!
