### ISSUE TITLE
error-correcting on direct RNA sequencing

### ISSUE THREAD

**Issue by jianghao0799** [ksahlin/isONcorrect#25]
Can it also be used on Oxford Nanopore Techology direct RNA reads?

**Comment by ksahlin** [comment]
Yes, it can!

**Comment by ksahlin** [comment]
See also this issue: https://github.com/ksahlin/isONcorrect/issues/15

**Comment by jianghao0799** [comment]
@ksahlin 
Thanks for ur reply!!
