### ISSUE TITLE
error during running:subprocess.CalledProcessError...returned non-zero exit status 1

### ISSUE THREAD

**Issue by huangziyan11111** [ksahlin/isONcorrect#3]
[error.txt](https://github.com/ksahlin/isONcorrect/files/4378674/error.txt)
Hi, I met an error during running: run_isoncorrect --t 32  --fastq_folder fastq_files  --outfolder correction/. The error information look like this:

92 (Time elapsed: 56938s)
creating correction/109
Running isoncorrect cl_id:109... multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/psd/biosoft/anaconda/envs/isoncorrect/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/psd/biosoft/anaconda/envs/isoncorrect/bin/run_isoncorrect", line 57, in isoncorrect
    "--T",  str(isoncorrect_algorithm_params["T"]) ], stderr=error_file, stdout=isoncorrect_out_file)
  File "/psd/biosoft/anaconda/envs/isoncorrect/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/time', '/psd/biosoft/anaconda/envs/isoncorrect/bin/isONcorrect', '--fastq', '/projects01/DS20010600001/02.transcriptome/01.cluster/isONclust/out.full_length/fastq_files/49.fastq', '--outfolder', 'correction/49', '--exact_instance_limit', '50', '--set_w_dynamically', '--k', '9', '--w', '10', '--xmin', '14', '--xmax', '80', '--T', '0.1']' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/psd/biosoft/anaconda/envs/isoncorrect/bin/run_isoncorrect", line 166, in <module>
    main(args)
  File "/psd/biosoft/anaconda/envs/isoncorrect/bin/run_isoncorrect", line 115, in main
    for x in pool.imap_unordered(isoncorrect, instances):
  File "/psd/biosoft/anaconda/envs/isoncorrect/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
subprocess.CalledProcessError: Command '['/usr/bin/time', '/psd/biosoft/anaconda/envs/isoncorrect/bin/isONcorrect', '--fastq', '/projects01/DS20010600001/02.transcriptome/01.cluster/isONclust/out.full_length/fastq_files/49.fastq', '--outfolder', 'correction/49', '--exact_instance_limit', '50', '--set_w_dynamically', '--k', '9', '--w', '10', '--xmin', '14', '--xmax', '80', '--T', '0.1']' returned non-zero exit status 1.

Please help me to solve, thank you!

**Comment by ksahlin** [comment]
Which version are you running (‘run_isoncorrect —version’). I recently (a few days ago) fixed a bug (#2) in version 0.0.6. Running this new version might help. 

If not, do you also have the possibility to share cluster 49.fastq with me so I can see if I can reproduce the bug?

**Comment by huangziyan11111** [comment]
the version is 0.0.3 and I install through "pip install isONcorrect"

**Comment by ksahlin** [comment]
Ok, I would then recommend to simply reinstall isONcorrect so that you get the newest version. Hopefully, that should fix it.

**Comment by ksahlin** [comment]
Sorry, the new version is **0.0.5** (I edited previous comments)

**Comment by ksahlin** [comment]
On a side note, you can specify `--keep_old` to keep the already corrected read-clusters when you restart. However, in your case, the new version (0.0.5) gives better results and is much less memory intense (to 0.0.3), so this time it should be worth it to recorrect all the clusters.

**Comment by huangziyan11111** [comment]
Ok, I have checked now the version is 0.0.5 and I will recorrect, hope bring you the good news

**Comment by zhuyiqin** [comment]
Hi, I just met the same error, and the version is 0.0.6

**Comment by huangziyan11111** [comment]
Sorry to renew the results now. Finally the script can work. :)
