### ISSUE TITLE
Extract representaive sequence from each cluster

### ISSUE THREAD

**Issue by timghaly** [ksahlin/isONcorrect#6]
Hi, is there a way to extract a single representative read (either a consensus or just the longest read) from each corrected cluster and concatenate them into a single file?
Thanks

**Comment by ksahlin** [comment]
Hi @timghaly,

If you are not strict with that it has to be the longest or a consensus read 100% of the time, you can run from the terminal after running the correction:

```
head -n 2 correction_outfolder/*/corrected_reads.fastq > all_representatives.fa
```

This will give you the first read in each file. isONclust sorts the reads in (rough) order of length and pre-correction quality, which means that it is very likely that the first read in each file is the longest and of high quality. 

However, in some cases where pychopper has not filtered out or "chopped" chimeric sequences, the first read can be a chimera. I'm not sure how to go about this - perhaps comparing the length difference within the first two/few sequences in each cluster and take the median one? Regardless, this is a post-correction decision that could be implemented in a separate script/command-line argument outside isONcorrect.

Best,
K
