### ISSUE TITLE
How to evaluate Accuracy of Reads ?

### ISSUE THREAD

**Issue by jkbenotmane** [ksahlin/isONcorrect#7]
Hi, 
I have a set of 10X Genomic barcoded unfragmented cDNA Sample and want to perform long-read sequencing on them. 
How can I measure the (current and following) accuracy of the Sequencing following isONcorrect?

**Comment by ksahlin** [comment]
Hi @jkbenotmane,

If you have a reference genome, you can align both the uncorrected and corrected reads to the genome with minimap2 using e.g.,

```
minimap2 --eqx -t 8 -ax splice -uf -k13 -w4 ref.fa  original_reads.fq >  original_reads.sam
minimap2 --eqx -t 8 -ax splice -uf -k13 -w4 ref.fa  corrected_reads.fq >  corrected_reads.sam
``` 
Then you can parse the cigar strings in the file to get the error rate (omitting `N` which are exon skips). I created a script for this if you have a GTF annotation [see here](https://github.com/ksahlin/isONcorrect/blob/master/scripts/evaluate_real_reads_to_genome.py). You can call it as 

```
python evaluate_real_reads_to_genome.py  original_reads.sam corrected_reads.sam  original_reads.fq  \
                                    corrected_reads.fq ref.fa isoncorrect_clusters annotation.gtf outfolder/
```

If you have a complete transcript database you can instead map the reads to the transcriptome and parse the cigar strings.
 from the sam file with alignments. In this case there should be no exons skips. But the alignment tasks is more complex so I prefer evaluating to a genome.

Best,
Kristoffer

**Comment by jkbenotmane** [comment]
Thank you very much for that comprehensive and conclusive answer! 

I have a very specific question and therefore want to evaluate to a transcriptome, can I use that as well as input for python evaluate_real_reads_to_genome.py?

**Comment by ksahlin** [comment]
It can work, depends on how good the aligner you are using is. 

However, I think [this script](https://github.com/ksahlin/isONcorrect/blob/master/scripts/evaluate_sirv_to_transcriptome.py) may better suit your purposes. We used it to align original and corrected SIRV reads to a reference transcriptome. Despite the name "evaluate_sirv_to_transcriptome.py" it works with any set of reference sequences (i.e. any transcriptome. Just make sure that your aligner do not allow intron gaps when aligning reads to transcripts. That is, gap extension should be high (e.g., there should be an intron-free mode in minimap2). This script is probably exactly what you want.

```
python evaluate_sirv_to_transcriptome.py  original_reads.sam corrected_reads.sam  \
                                           original_reads.fq  corrected_reads.fq  \
                                           ref_transcriptome.fa outfolder 
```

**Comment by ksahlin** [comment]
oh, and you need to have `=/X` in your cigars, not `M`. This can be produced in minimap2 with flag `--eqx`

**Comment by jkbenotmane** [comment]
Again thank you! That worked really well!
I aligned with minimap using following Presets:

minimap2\
-ax map-ont\ 
--eqx\
-t 8\
-uf\
-k13\
-w4\
/Dropbox/Alignment_References/Reference/IMGT+C.fa\
/Dropbox/User/Projects/Sequencing/Samples/Samples/Sample9/isONcorrect/Sample9_sup_sample_1000.fastq >  Sample9_sample.sam

Then extracted only those Reads that align (because I am only interested in them) and outputtet them as fastq:

samtools view -b Sample9_sample.sam > Sample9_sample.bam
samtools view -b -F 4 Sample9_sample.bam > Sample9_sample_mapped.bam
samtools view -h -o Sample9_sample_mapped.sam Sample9_sample_mapped.bam
samtools fastq Sample9_sample_mapped.bam > Sample9_sample_mapped.fastq

Then I trained a pHMM Model with Custom Primers:

hp_bootstrap.py \
    -f Dropbox/User/Projects/Sequencing/Samples/Samples/Sample9/isONcorrect/pychopper/10X_Primers/10XPrimers_pychopper.fa\
    -o Dropbox/User/Projects/Sequencing/Samples/Samples/Sample9/isONcorrect/pychopper/10X_Primers/Hammerpede_Model\
    -i fastq\
    Dropbox/User/Projects/Sequencing/Samples/Samples/Sample9/isONcorrect/Samtools/Sample9_sample_mapped.fastq

Then I used the Model to recover Full Reads like so:

cdna_classifier.py\
    -m phmm\
    -g Dropbox/User/Projects/Sequencing/Samples/Sampless/Sample9/isONcorrect/pychopper/10X_partial_Primers/Hammerpede_Model/10XPrimers_pychopper.hmm\
    -c Dropbox/User/Projects/Sequencing/Samples/Sampless/Sample9/isONcorrect/pychopper/10X_partial_Primers/10XPrimers_pychopper_configuration.txt\
    Dropbox/User/Projects/Sequencing/Samples/Sampless/Sample9/isONcorrect/Samtools/Sample9_sample_mapped.fastq \
    Sample9_sample_mapped_full_length_output.fastq

Then performed isONClust:
isONclust --t 8\
          --ont\
          --fastq Dropbox/User/Projects/Sequencing/Samples/Samples/Sample9/isONcorrect/pychopper/10X_partial_Primers/Full_Length_cDNA/Sample9_sample_mapped_full_length_output.fastq\
          --outfolder ./clustering

Combined the Reads:
isONclust write_fastq --N 1\
        --clusters Dropbox/User/Projects/Sequencing/Samples/Sample/Sample9/isONcorrect/pychopper/10X_partial_Primers/isONclust/clustering/final_clusters.tsv \
        --fastq Dropbox/User/Projects/Sequencing/Samples/Sample/Sample9/isONcorrect/pychopper/10X_partial_Primers/Full_Length_cDNA/Sample9_sample_mapped_full_length_output.fastq\
        --outfolder Dropbox/User/Projects/Sequencing/Samples/Sample/Sample9/isONcorrect/pychopper/10X_partial_Primers/isONclust/Full_Length_isonclust/fastq_files


isONCorrected them:

run_isoncorrect\
    --t 8\
    --fastq_folder /mnt/d/Dropbox/User/Projects/Sequencing/Samples/Samples/Sample9/isONcorrect/pychopper/10X_partial_Primers/isONclust/Full_Length_isonclust/fastq_files\
    --outfolder /mnt/d/Dropbox/User/Projects/Sequencing/Samples/Samples/Sample9/isONcorrect/pychopper/10X_partial_Primers/isONcorrect

And Combined Them:

touch /mnt/d/Dropbox/KBJasim/Projects/Capture_Sequencing/Samples/SpaTCR/SPTCR9/isONcorrect/pychopper/10X_partial_Primers/isONcorrect
for f in /mnt/d/Dropbox/KBJasim/Projects/Capture_Sequencing/Samples/SpaTCR/SPTCR9/isONcorrect/pychopper/10X_partial_Primers/isONcorrect/*/corrected_reads.fastq; 
do 
  cat ${f} >> /mnt/d/Dropbox/KBJasim/Projects/Capture_Sequencing/Samples/SpaTCR/SPTCR9/isONcorrect/pychopper/10X_partial_Primers/isONcorrect/Corrected_merge/SPTCR9_10X_partial_corrected.fastq
done


Then performed the Pipeline you recommended me on it:

python /mnt/d/Dropbox/User/Projects/Sequencing/Analysis/Analysis_Tools/isONcorrect/scripts/evaluate_sirv_to_transcriptome.py \
                /mnt/d/Dropbox/User/Projects/Sequencing/Samples/SpaTCR/Sample9/isONcorrect/Samtools/Sample9_sample_mapped.sam \
                /mnt/d/Dropbox/User/Projects/Sequencing/Samples/SpaTCR/Sample9/isONcorrect/pychopper/10X_partial_Primers/Correction_Evaluation/Sample9_sample_mapped_corrected_Reads.sam \
                /mnt/d/Dropbox/User/Projects/Sequencing/Samples/SpaTCR/Sample9/isONcorrect/SPATCR9_sup_sample_1000.fastq \
                /mnt/d/Dropbox/User/Projects/Sequencing/Samples/SpaTCR/Sample9/isONcorrect/pychopper/10X_partial_Primers/isONcorrect/Corrected_merge/Sample9_10X_partial_corrected.fastq \
                /mnt/d/Dropbox/Alignment_References/IMGT_Reference/IMGT+C.fa\
                /mnt/d/Dropbox/User/Projects/Sequencing/Samples/SpaTCR/Sample9/isONcorrect/pychopper/10X_partial_Primers/Correction_Evaluation


Last Question: With which Script did you produce the Plots from the NatComPaper (for exp. 1b) as there is many Scripts named plots.py ?

Projects/Capture_Sequencing/TCR_Analysis/TCR_Analysis_Tools/isONcorrect/evaluation/plots.py
=> considering this one: what is meant by the required Argument "Dataset"
Projects/Capture_Sequencing/TCR_Analysis/TCR_Analysis_Tools/isONcorrect/evaluation_sirv/plots.py
Projects/Capture_Sequencing/TCR_Analysis/TCR_Analysis_Tools/isONcorrect/scripts/plots.py
Projects/Capture_Sequencing/TCR_Analysis/TCR_Analysis_Tools/isONcorrect/scripts/make_all_plots.sh

**Comment by ksahlin** [comment]
Great that it worked well!

This [plots.py script](https://github.com/ksahlin/isONcorrect/blob/master/evaluation/plots.py)

Run as

```
python plots.py  input_csv_file  outfolder experiment_name
```

experiment_name can be e.g. `SPTCR9_10X`. `input_csv_file` is the output produced by the evaluation script.

Best,
K

**Comment by jkbenotmane** [comment]
Thank you Kristoffer! 
I could produce the Plot.

But correct me if I am wrong: the Experiment_name should by sirv if using the Script evaluate_sirv_to_transcriptome.py like so:

python3 /User/Projects/Sequencing/Analysis/Analysis_Tools/isONcorrect/evaluation/plots.py\
    /User/Projects/Sequencing/Samples/Samples/Sample9/isONcorrect/results_per_read_to_transcriptome.csv\
    ./ \
    sirv

Otherwise expected Columns from get_error_rates won´t be found.

**Comment by ksahlin** [comment]
Ah, you are right! I should factor out this script for general use.
